// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// AccessInfo is an autogenerated mock type for the AccessInfo type
type AccessInfo struct {
	mock.Mock
}
