// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// BuilderODR is an autogenerated mock type for the BuilderODR type
type BuilderODR struct {
	mock.Mock
}

// BuildODRFunc provides a mock function with given fields:
func (_m *BuilderODR) BuildODRFunc() interface{} {
	ret := _m.Called()

	var r0 interface{}
	if rf, ok := ret.Get(0).(func() interface{}); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	return r0
}
