// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// OutParameter is an autogenerated mock type for the OutParameter type
type OutParameter struct {
	mock.Mock
}

// isOutParameter provides a mock function with given fields:
func (_m *OutParameter) isOutParameter() {
	_m.Called()
}
