// Code generated by mockery v1.1.2. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// RunningTask is an autogenerated mock type for the RunningTask type
type RunningTask struct {
	mock.Mock
}
